### ISSUE TITLE
Demo upload fails with "Failed to execute 'readAsArrayBuffer' on 'FileReader'"

### ISSUE THREAD

**Issue by jevakallio** [dylanarmstrong/puz#1]
Hi! Thanks for creating this library, I found it on npm while building out a Crossword-related project.

I haven't used the library in my own code yet, but I found an issue while testing it out on the official demo site.

## Issue 

When using the [demo site](https://dylan.is/crossword), some `.puz` files cause an error **Uncaught TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'**, while others work fine.

Example of failing puzzle: 
https://www.nytimes.com/crosswords/game/daily/2020/06/09

Example of a working puzzle:
https://www.nytimes.com/crosswords/game/daily/2020/03/09

Both files open fine in Across Lite. Neither contains any weird elements (circles, gray squares, rebus answers, descriptions, etc.)

If you don't have access to downloading `.puz` files from NY Times, I can send you a failing file (don't want to upload publicly due to licensing concerns).

### Browser details:
- Google Chrome Version 86.0.4240.111 (Official Build) (MacOS, x86_64)
- Firefox 80.0.1 (64-bit)

### Steps to reproduce
- Acquire a `.puz` file, e.g. by downloading from NYT website (requires a NY Times Crossword account)
- Navigate to https://dylan.is/crossword
- Upload `.puz` file to demo site (either drag and drop or file upload button)

Expected outcome: Puzzle is displayed.

Actual outcome: Nothing happens in the UI. Chrome developer tools show below error.

### Stack trace:
```
Uncaught TypeError: Failed to execute 'readAsArrayBuffer' on 'FileReader': parameter 1 is not of type 'Blob'.
    at oe (index.jsx:87)
    at Object.Wt (react-dom.production.min.js:52)
    at qt (react-dom.production.min.js:52)
    at react-dom.production.min.js:53
    at Cr (react-dom.production.min.js:100)
    at Pr (react-dom.production.min.js:101)
    at react-dom.production.min.js:113
    at Lt (react-dom.production.min.js:292)
    at react-dom.production.min.js:50
    at Mr (react-dom.production.min.js:105)
```

**Comment by dylanarmstrong** [comment]
Hey @jevakallio, thanks for the issue report.

I'm looking into this now, and it seems to be an issue with this puzzle being 15x16.

**Comment by dylanarmstrong** [comment]
Hey, this should be good now, want to test it out?

**Comment by jevakallio** [comment]
@dylanarmstrong yup, that works! 👏
